server:
  port: 443
  ssl:
    enabled: true
    key-store: src/main/resources/keystore.p12
    key-store-type: PKCS12
    key-store-password: gangnam
    key-alias: tomcat
spring:
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
  config:
    import: "classpath:application-db.yml"